### ISSUE TITLE
Callback after all changes have occured

### ISSUE THREAD

**Issue by EmilEriksen** [bevry/watchr#65]
When I move, change the name of or delete a directory, the change event obviously occurs a bunch of times. Is there anyway I can execute a function after it's done?

Thank you!

**Comment by balupton** [comment]
Would you be able to provide more details about what you got and what you were expecting? As I'm not sure what you mean.

Additionally, v3.0.0 was just released which is a major rewrite, perhaps it will resolve this issue 👍

Sorry for the late response on this, 2014 and 2015 were hard years for me!

Closing due to age. Happy to re-open.
